# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main: []
  # - name: Home
  #   url: /
  #   weight: 10
  # - name: Team
  #   url: /team
  #   weight: 20
  # - name: Blog
  #   url: /blog
  #   weight: 30
